CREATE DATABASE QuanLyBanHang;

CREATE TABLE SANPHAM (
    MaSP INT PRIMARY KEY IDENTITY(1,1), 
    TenSP NVARCHAR(100) NOT NULL,
    DonGia DECIMAL(18, 2) NOT NULL,
    SoLuongTon INT DEFAULT 0,
    MoTa NVARCHAR(500),
    DaXoa BIT DEFAULT 0 -- 0: Đang bán, 1: Đã xóa
);
GO


CREATE TABLE KHACHHANG (
    MaKH INT PRIMARY KEY IDENTITY(1,1),
    HoTen NVARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(20),
    DiaChi NVARCHAR(255),
    DaXoa BIT DEFAULT 0 --xóa mềm dlieu
);
GO


CREATE TABLE DONHANG (
    MaDonHang INT PRIMARY KEY IDENTITY(1,1),
    NgayTao DATETIME DEFAULT GETDATE(),
    TongTien DECIMAL(18, 2),
    TrangThai NVARCHAR(50),
    MaKH INT -- Khóa ngoại 
);
ALTER TABLE DONHANG
ADD GhiChu NVARCHAR(500) NULL; -- cho phép để trống (NULL)


CREATE TABLE CHITIETHOADON (
    MaDonHang INT,
    MaSP INT,
    SoLuong INT NOT NULL,
    DonGiaTaiThoiDiemMua DECIMAL(18, 2) NOT NULL,
    PRIMARY KEY (MaDonHang, MaSP)
);


-- liên kết từ DONHANG đến KHACHHANG
ALTER TABLE DONHANG
ADD CONSTRAINT FK_DonHang_KhachHang
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);

-- liên kết từ CHITIETHOADON đến DONHANG
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_ChiTiet_DonHang
FOREIGN KEY (MaDonHang) REFERENCES DONHANG(MaDonHang);

-- liên kết từ CHITIETHOADON đến SANPHAM
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_ChiTiet_SanPham
FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP);
GO

ALTER TABLE DONHANG
ADD NguoiBan VARCHAR(50);
GO

-- tạo khóa ngoại để đảm bảo người bán phải là nhân viên có thật
ALTER TABLE DONHANG
ADD CONSTRAINT FK_DonHang_NguoiDung
FOREIGN KEY (NguoiBan) REFERENCES NGUOIDUNG(TenDangNhap);
GO

select*from DONHANG
select*from SANPHAM
select*from KHACHHANG
select*from CHITIETHOADON
